databases:
  - name: mysql
    ipAllowList: []

services:
  - type: web
    name: rails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_KEY_MASTER
        sync: false 
      - key: DATABASE_URL
        fromDatabase:
          name: mysql
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free 
    maxmemoryPolicy: noeviction

